### ISSUE TITLE
Running the code

### ISSUE THREAD

**Issue by shreyanshgeek** [ntrivix/Mini-Java-Compiler#1]
I am stuck in this since yesterday and not finding any way to run this code. Please help as to how to run the code and get an output. URGENT

**Comment by ntrivix** [comment]
Hi @shreyanshgeek ,

Please download latest master and call `make`, that should work.

**Comment by shreyanshgeek** [comment]
Thanks!
Can you please tell me what is exact output we are expected to get? It is giving the Symbol table only.

**Comment by ntrivix** [comment]
It's giving Symbol table and compilation errors if there are any. This was a university project and only requirements were to do lexical and semantic analysis. I think you can easily extend this to generate a program executable.
